ALTER TABLE users
ALTER COLUMN datecreated SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE questions
ALTER COLUMN createdat SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE answers
ALTER COLUMN createdat SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Users
DROP COLUMN Email;