name: Build and Release - DB
on:
  push:
    #branches:
      #- 'db/*'
permissions:
  id-token: write
  contents: read

jobs:
  #deploy:
  #  name: Build and Deploy Database
  #  needs: migration
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
#
  #  steps:
  #    - name: Git checkout 
  #      uses: actions/checkout@v3
#
  #    - name: Configure AWS credentials from AWS account
  #      uses: aws-actions/configure-aws-credentials@v4
  #      with:
  #        role-to-assume: ${{ secrets.AWS_ROLE }}
  #        aws-region: ${{ secrets.AWS_REGION }}
  #        role-session-name: Github-OIDC-TERRAFORM
  #        audience: sts.amazonaws.com
#
  #    - name: Setup Terraform
  #      uses: hashicorp/setup-terraform@v2
  #      with:
  #        terraform_version: 1.6.6
#
  #    - name: Terraform Init 
  #      id: init
  #      working-directory: ./terraform
  #      run: terraform init 
#
  #    - name: Terraform Validate
  #      id: validate
  #      working-directory: ./terraform
  #      run: terraform validate
#
  #    - name: Terraform Plan
  #      id: plan
  #      working-directory: ./terraform
  #      run: terraform plan
#
  #    - name: Terraform Apply
  #      working-directory: ./terraform
  #      run: terraform apply -auto-approve

  migration:
    name: Run Flyway Migration
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
  
      - name: Run Live Flyway Migrations
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.DB_URL }}
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          locations:  filesystem:./migrations
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true